channels:
  - conda-forge

dependencies:
  # packages listed here are fetched and installed from conda-forge. 
  - python=3.12.3          
  - pip=23.2.1  
  - nodejs=22.11.0
  - pip:
    # packlages listed here are fetched from pypi.org and installed using pip.
    - robotframework==7.1.1
    - robotframework-browser==19.1
    - robotframework-crypto==0.3.0
    - pyotp==2.9.0
    - robotframework-tidy
    - requests
    - beautifulsoup4
    - pyzbar
    - pillow

rccPostInstall:
  - rfbrowser init   # Initialization command for Playwright (npm)

