channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip=23.2.1
  - pip:
    - robotframework==7.1.1
    - robotframework-imagehorizonlibrary==1.0
    - PyScreeze==0.1.29
    - PyAutoGUI==0.9.54